//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/SequenceSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SequenceSchema.xsd", IsNullable=false)]
public partial class DatabaseObjects {
    
    private DatabaseObjectsSQLObject[] sQLObjectField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SQLObject")]
    public DatabaseObjectsSQLObject[] SQLObject {
        get {
            return this.sQLObjectField;
        }
        set {
            this.sQLObjectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/SequenceSchema.xsd")]
public partial class DatabaseObjectsSQLObject { 
    
    private DatabaseObjectsSQLObjectType typeField;
    
    private string nameField;

    private string isGenerated;
    
    private string ignore;

    private DatabaseObjectsSQLObjectProcess processField;
    
    public DatabaseObjectsSQLObject() {
        this.typeField = DatabaseObjectsSQLObjectType.Unknown;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(DatabaseObjectsSQLObjectType.Unknown)]
    public DatabaseObjectsSQLObjectType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IsGenerated
    {
        get
        {
            return this.isGenerated;
        }
        set
        {
            this.isGenerated = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ignore
    {
        get
        {
            return this.ignore;
        }
        set
        {
            this.ignore = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DatabaseObjectsSQLObjectProcess Process
    {
        get
        {
            return this.processField;
        }
        set
        {
            this.processField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/SequenceSchema.xsd")]
public enum DatabaseObjectsSQLObjectType {
    
    /// <remarks/>
    Table,

    /// <remarks/>
    TableKey,
    
    /// <remarks/>
    Constraint,
    
    /// <remarks/>
    Index,
    
    /// <remarks/>
    Trigger,
    
    /// <remarks/>
    Type,
    
    /// <remarks/>
    FunctionScalar,
    
    /// <remarks/>
    FunctionTable,
    
    /// <remarks/>
    View,
    
    /// <remarks/>
    StoredProcedure,

    /// <remarks/>
    UpgradeVersion,

    /// <remarks/>
    Script,

    /// <remarks/>
    Drop,

    /// <remarks/>
    Unknown,
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/SequenceSchema.xsd")]
public enum DatabaseObjectsSQLObjectProcess
{

    /// <remarks/>
    NonOrdered,

    /// <remarks/>
    Single,

    /// <remarks/>
    GenerateTableFiles,

    /// <remarks/>
    GenerateNonTableFiles,

    /// <remarks/>
    UpdateVariableTables,

    /// <remarks/>
    RemoveDefaultLayout,

    /// <remarks/>
    ClearCustomConversions,

    /// <remarks/>
    ExecuteDeferredCustomConversions,

    /// <remarks/>
    LoadCalcsAndVariables
}
