IF (SELECT COUNT(*) FROM STORES WHERE ACTIVE_IND='1' AND ST_RID IN (SELECT ST_RID FROM STORES_TO_BE_DELETED)) > 0
BEGIN
   SELECT 'The following stores are ACTIVE and will be set to INACTIVE'
   SELECT ST_ID, STORE_NAME FROM STORES WHERE ACTIVE_IND='1' AND ST_RID IN (SELECT ST_RID FROM STORES_TO_BE_DELETED)
END
 SELECT 'The following stores have been marked for deletion:'
 UPDATE STORES SET STORE_DELETE_IND='1', ACTIVE_IND = '0' WHERE ST_RID IN (SELECT ST_RID FROM STORES_TO_BE_DELETED)
 SELECT ST_ID, STORE_NAME FROM STORES WHERE  ST_RID IN (SELECT ST_RID FROM STORES_TO_BE_DELETED)