ALTER TABLE STORE_FORECAST_WEEK0
drop constraint STORE_FORECAST_WEEK0_HN_MOD
go
ALTER TABLE STORE_FORECAST_WEEK0 WITH CHECK 
add constraint STORE_FORECAST_WEEK0_HN_MOD check ([HN_MOD] = 0)
go

ALTER TABLE STORE_FORECAST_WEEK1
drop constraint STORE_FORECAST_WEEK1_HN_MOD
go
ALTER TABLE STORE_FORECAST_WEEK1 WITH CHECK 
add constraint STORE_FORECAST_WEEK1_HN_MOD check ([HN_MOD] = 1)
go

ALTER TABLE STORE_FORECAST_WEEK2
drop constraint STORE_FORECAST_WEEK2_HN_MOD
go
ALTER TABLE STORE_FORECAST_WEEK2 WITH CHECK 
add constraint STORE_FORECAST_WEEK2_HN_MOD check ([HN_MOD] = 2)
go

ALTER TABLE STORE_FORECAST_WEEK3
drop constraint STORE_FORECAST_WEEK3_HN_MOD
go
ALTER TABLE STORE_FORECAST_WEEK3 WITH CHECK 
add constraint STORE_FORECAST_WEEK3_HN_MOD check ([HN_MOD] = 3)
go

ALTER TABLE STORE_FORECAST_WEEK4
drop constraint STORE_FORECAST_WEEK4_HN_MOD
go
ALTER TABLE STORE_FORECAST_WEEK4 WITH CHECK 
add constraint STORE_FORECAST_WEEK4_HN_MOD check ([HN_MOD] = 4)
go

ALTER TABLE STORE_FORECAST_WEEK5
drop constraint STORE_FORECAST_WEEK5_HN_MOD
go
ALTER TABLE STORE_FORECAST_WEEK5 WITH CHECK 
add constraint STORE_FORECAST_WEEK5_HN_MOD check ([HN_MOD] = 5)
go

ALTER TABLE STORE_FORECAST_WEEK6
drop constraint STORE_FORECAST_WEEK6_HN_MOD
go
ALTER TABLE STORE_FORECAST_WEEK6 WITH CHECK 
add constraint STORE_FORECAST_WEEK6_HN_MOD check ([HN_MOD] = 6)
go

ALTER TABLE STORE_FORECAST_WEEK7
drop constraint STORE_FORECAST_WEEK7_HN_MOD
go
ALTER TABLE STORE_FORECAST_WEEK7 WITH CHECK 
add constraint STORE_FORECAST_WEEK7_HN_MOD check ([HN_MOD] = 7)
go

ALTER TABLE STORE_FORECAST_WEEK8
drop constraint STORE_FORECAST_WEEK8_HN_MOD
go
ALTER TABLE STORE_FORECAST_WEEK8 WITH CHECK 
add constraint STORE_FORECAST_WEEK8_HN_MOD check ([HN_MOD] = 8)
go

ALTER TABLE STORE_FORECAST_WEEK9
drop constraint STORE_FORECAST_WEEK9_HN_MOD
go
ALTER TABLE STORE_FORECAST_WEEK9 WITH CHECK 
add constraint STORE_FORECAST_WEEK9_HN_MOD check ([HN_MOD] = 9)
go

ALTER TABLE STORE_HISTORY_WEEK0
drop constraint STORE_HISTORY_WEEK0_HN_MOD
go
ALTER TABLE STORE_HISTORY_WEEK0 WITH CHECK 
add constraint STORE_HISTORY_WEEK0_HN_MOD check ([HN_MOD] = 0)
go

ALTER TABLE STORE_HISTORY_WEEK1
drop constraint STORE_HISTORY_WEEK1_HN_MOD
go
ALTER TABLE STORE_HISTORY_WEEK1 WITH CHECK 
add constraint STORE_HISTORY_WEEK1_HN_MOD check ([HN_MOD] = 1)
go

ALTER TABLE STORE_HISTORY_WEEK2
drop constraint STORE_HISTORY_WEEK2_HN_MOD
go
ALTER TABLE STORE_HISTORY_WEEK2 WITH CHECK 
add constraint STORE_HISTORY_WEEK2_HN_MOD check ([HN_MOD] = 2)
go

ALTER TABLE STORE_HISTORY_WEEK3
drop constraint STORE_HISTORY_WEEK3_HN_MOD
go
ALTER TABLE STORE_HISTORY_WEEK3 WITH CHECK 
add constraint STORE_HISTORY_WEEK3_HN_MOD check ([HN_MOD] = 3)
go

ALTER TABLE STORE_HISTORY_WEEK4
drop constraint STORE_HISTORY_WEEK4_HN_MOD
go
ALTER TABLE STORE_HISTORY_WEEK4 WITH CHECK 
add constraint STORE_HISTORY_WEEK4_HN_MOD check ([HN_MOD] = 4)
go

ALTER TABLE STORE_HISTORY_WEEK5
drop constraint STORE_HISTORY_WEEK5_HN_MOD
go
ALTER TABLE STORE_HISTORY_WEEK5 WITH CHECK 
add constraint STORE_HISTORY_WEEK5_HN_MOD check ([HN_MOD] = 5)
go

ALTER TABLE STORE_HISTORY_WEEK6
drop constraint STORE_HISTORY_WEEK6_HN_MOD
go
ALTER TABLE STORE_HISTORY_WEEK6 WITH CHECK 
add constraint STORE_HISTORY_WEEK6_HN_MOD check ([HN_MOD] = 6)
go

ALTER TABLE STORE_HISTORY_WEEK7
drop constraint STORE_HISTORY_WEEK7_HN_MOD
go
ALTER TABLE STORE_HISTORY_WEEK7 WITH CHECK 
add constraint STORE_HISTORY_WEEK7_HN_MOD check ([HN_MOD] = 7)
go

ALTER TABLE STORE_HISTORY_WEEK8
drop constraint STORE_HISTORY_WEEK8_HN_MOD
go
ALTER TABLE STORE_HISTORY_WEEK8 WITH CHECK 
add constraint STORE_HISTORY_WEEK8_HN_MOD check ([HN_MOD] = 8)
go

ALTER TABLE STORE_HISTORY_WEEK9
drop constraint STORE_HISTORY_WEEK9_HN_MOD
go
ALTER TABLE STORE_HISTORY_WEEK9 WITH CHECK 
add constraint STORE_HISTORY_WEEK9_HN_MOD check ([HN_MOD] = 9)
go

ALTER TABLE STORE_HISTORY_DAY0
drop constraint STORE_HISTORY_DAY0_HN_MOD
go
ALTER TABLE STORE_HISTORY_DAY0 WITH CHECK 
add constraint STORE_HISTORY_DAY0_HN_MOD check ([HN_MOD] = 0)
go

ALTER TABLE STORE_HISTORY_DAY1
drop constraint STORE_HISTORY_DAY1_HN_MOD
go
ALTER TABLE STORE_HISTORY_DAY1 WITH CHECK 
add constraint STORE_HISTORY_DAY1_HN_MOD check ([HN_MOD] = 1)
go

ALTER TABLE STORE_HISTORY_DAY2
drop constraint STORE_HISTORY_DAY2_HN_MOD
go
ALTER TABLE STORE_HISTORY_DAY2 WITH CHECK 
add constraint STORE_HISTORY_DAY2_HN_MOD check ([HN_MOD] = 2)
go

ALTER TABLE STORE_HISTORY_DAY3
drop constraint STORE_HISTORY_DAY3_HN_MOD
go
ALTER TABLE STORE_HISTORY_DAY3 WITH CHECK 
add constraint STORE_HISTORY_DAY3_HN_MOD check ([HN_MOD] = 3)
go

ALTER TABLE STORE_HISTORY_DAY4
drop constraint STORE_HISTORY_DAY4_HN_MOD
go
ALTER TABLE STORE_HISTORY_DAY4 WITH CHECK 
add constraint STORE_HISTORY_DAY4_HN_MOD check ([HN_MOD] = 4)
go

ALTER TABLE STORE_HISTORY_DAY5
drop constraint STORE_HISTORY_DAY5_HN_MOD
go
ALTER TABLE STORE_HISTORY_DAY5 WITH CHECK 
add constraint STORE_HISTORY_DAY5_HN_MOD check ([HN_MOD] = 5)
go

ALTER TABLE STORE_HISTORY_DAY6
drop constraint STORE_HISTORY_DAY6_HN_MOD
go
ALTER TABLE STORE_HISTORY_DAY6 WITH CHECK 
add constraint STORE_HISTORY_DAY6_HN_MOD check ([HN_MOD] = 6)
go

ALTER TABLE STORE_HISTORY_DAY7
drop constraint STORE_HISTORY_DAY7_HN_MOD
go
ALTER TABLE STORE_HISTORY_DAY7 WITH CHECK 
add constraint STORE_HISTORY_DAY7_HN_MOD check ([HN_MOD] = 7)
go

ALTER TABLE STORE_HISTORY_DAY8
drop constraint STORE_HISTORY_DAY8_HN_MOD
go
ALTER TABLE STORE_HISTORY_DAY8 WITH CHECK 
add constraint STORE_HISTORY_DAY8_HN_MOD check ([HN_MOD] = 8)
go

ALTER TABLE STORE_HISTORY_DAY9
drop constraint STORE_HISTORY_DAY9_HN_MOD
go
ALTER TABLE STORE_HISTORY_DAY9 WITH CHECK 
add constraint STORE_HISTORY_DAY9_HN_MOD check ([HN_MOD] = 9)
go