/*=======================================================================================*/
--  Drop and Re-add primary key constraints on FORECAST tables
/*=======================================================================================*/

exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK0', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK1', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK2', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK3', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK4', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK5', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK6', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK7', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK8', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK9', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_FORECAST_WEEK_LOCK', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'CHAIN_FORECAST_WEEK', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'CHAIN_FORECAST_WEEK_LOCK', 'PRIMARY KEY';
go

ALTER TABLE [dbo].[STORE_FORECAST_WEEK0] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK0_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_FORECAST_WEEK1] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK1_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_FORECAST_WEEK2] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK2_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_FORECAST_WEEK3] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK3_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_FORECAST_WEEK4] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK4_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_FORECAST_WEEK5] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK5_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_FORECAST_WEEK6] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK6_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_FORECAST_WEEK7] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK7_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_FORECAST_WEEK8] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK8_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_FORECAST_WEEK9] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK9_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_FORECAST_WEEK_LOCK] 
  ADD CONSTRAINT [STORE_FORECAST_WEEK_LOCK_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID],
		[ST_RID]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CHAIN_FORECAST_WEEK] 
  ADD CONSTRAINT [CHAIN_FORECAST_WEEK_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CHAIN_FORECAST_WEEK_LOCK] 
  ADD CONSTRAINT [CHAIN_FORECAST_WEEK_LOCK_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[FV_RID],
		[TIME_ID]
	)  WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

/*=======================================================================================*/
--  Drop and Re-add primary key constraints on HISTORY tables
/*=======================================================================================*/

exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_DAY0', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_DAY1', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_DAY2', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_DAY3', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_DAY4', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_DAY5', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_DAY6', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_DAY7', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_DAY8', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_DAY9', 'PRIMARY KEY';
go

exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_WEEK0', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_WEEK1', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_WEEK2', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_WEEK3', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_WEEK4', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_WEEK5', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_WEEK6', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_WEEK7', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_WEEK8', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'STORE_HISTORY_WEEK9', 'PRIMARY KEY';
go
exec SP_MID_DROP_CONSTRAINTS 'CHAIN_HISTORY_WEEK', 'PRIMARY KEY';
go

ALTER TABLE [dbo].[STORE_HISTORY_DAY0] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_DAY0_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 65)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_DAY1] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_DAY1_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 65)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_DAY2] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_DAY2_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 65)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_DAY3] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_DAY3_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 65)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_DAY4] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_DAY4_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 65)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_DAY5] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_DAY5_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 65)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_DAY6] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_DAY6_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 65)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_DAY7] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_DAY7_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 65)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_DAY8] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_DAY8_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 65)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_DAY9] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_DAY9_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 65)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_WEEK0] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_WEEK0_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_WEEK1] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_WEEK1_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_WEEK2] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_WEEK2_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_WEEK3] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_WEEK3_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_WEEK4] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_WEEK4_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_WEEK5] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_WEEK5_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_WEEK6] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_WEEK6_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_WEEK7] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_WEEK7_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_WEEK8] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_WEEK8_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[STORE_HISTORY_WEEK9] WITH NOCHECK ADD 
	CONSTRAINT [STORE_HISTORY_WEEK9_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID],
		[ST_RID],
		[HN_MOD]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CHAIN_HISTORY_WEEK] ADD 
	CONSTRAINT [CHAIN_HISTORY_WEEK_PK] PRIMARY KEY  CLUSTERED 
	(
		[HN_RID],
		[TIME_ID]
	) WITH (FILLFACTOR = 80) ON [PRIMARY] 
GO
