DROP INDEX [dbo].[STORE_HISTORY_DAY0].STORE_HISTORY_DAY0_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_DAY0_ST_IDX] ON [dbo].[STORE_HISTORY_DAY0]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 65) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_DAY1].STORE_HISTORY_DAY1_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_DAY1_ST_IDX] ON [dbo].[STORE_HISTORY_DAY1]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 65) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_DAY2].STORE_HISTORY_DAY2_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_DAY2_ST_IDX] ON [dbo].[STORE_HISTORY_DAY2]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 65) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_DAY3].STORE_HISTORY_DAY3_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_DAY3_ST_IDX] ON [dbo].[STORE_HISTORY_DAY3]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 65) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_DAY4].STORE_HISTORY_DAY4_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_DAY4_ST_IDX] ON [dbo].[STORE_HISTORY_DAY4]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 65) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_DAY5].STORE_HISTORY_DAY5_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_DAY5_ST_IDX] ON [dbo].[STORE_HISTORY_DAY5]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 65) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_DAY6].STORE_HISTORY_DAY6_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_DAY6_ST_IDX] ON [dbo].[STORE_HISTORY_DAY6]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 65) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_DAY7].STORE_HISTORY_DAY7_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_DAY7_ST_IDX] ON [dbo].[STORE_HISTORY_DAY7]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 65) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_DAY8].STORE_HISTORY_DAY8_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_DAY8_ST_IDX] ON [dbo].[STORE_HISTORY_DAY8]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 65) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_DAY9].STORE_HISTORY_DAY9_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_DAY9_ST_IDX] ON [dbo].[STORE_HISTORY_DAY9]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 65) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_WEEK0].STORE_HISTORY_WEEK0_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_WEEK0_ST_IDX] ON [dbo].[STORE_HISTORY_WEEK0]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_WEEK1].STORE_HISTORY_WEEK1_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_WEEK1_ST_IDX] ON [dbo].[STORE_HISTORY_WEEK1]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_WEEK2].STORE_HISTORY_WEEK2_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_WEEK2_ST_IDX] ON [dbo].[STORE_HISTORY_WEEK2]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_WEEK3].STORE_HISTORY_WEEK3_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_WEEK3_ST_IDX] ON [dbo].[STORE_HISTORY_WEEK3]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_WEEK4].STORE_HISTORY_WEEK4_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_WEEK4_ST_IDX] ON [dbo].[STORE_HISTORY_WEEK4]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_WEEK5].STORE_HISTORY_WEEK5_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_WEEK5_ST_IDX] ON [dbo].[STORE_HISTORY_WEEK5]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_WEEK6].STORE_HISTORY_WEEK6_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_WEEK6_ST_IDX] ON [dbo].[STORE_HISTORY_WEEK6]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_WEEK7].STORE_HISTORY_WEEK7_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_WEEK7_ST_IDX] ON [dbo].[STORE_HISTORY_WEEK7]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_WEEK8].STORE_HISTORY_WEEK8_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_WEEK8_ST_IDX] ON [dbo].[STORE_HISTORY_WEEK8]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_HISTORY_WEEK9].STORE_HISTORY_WEEK9_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_HISTORY_WEEK9_ST_IDX] ON [dbo].[STORE_HISTORY_WEEK9]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK0].STORE_FORECAST_WEEK0_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK0_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK0]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK1].STORE_FORECAST_WEEK1_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK1_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK1]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK2].STORE_FORECAST_WEEK2_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK2_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK2]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK3].STORE_FORECAST_WEEK3_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK3_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK3]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK4].STORE_FORECAST_WEEK4_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK4_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK4]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK5].STORE_FORECAST_WEEK5_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK5_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK5]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK6].STORE_FORECAST_WEEK6_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK6_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK6]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK7].STORE_FORECAST_WEEK7_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK7_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK7]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK8].STORE_FORECAST_WEEK8_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK8_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK8]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK9].STORE_FORECAST_WEEK9_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK9_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK9]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_FORECAST_WEEK_LOCK].STORE_FORECAST_WEEK_LOCK_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_FORECAST_WEEK_LOCK_ST_IDX] ON [dbo].[STORE_FORECAST_WEEK_LOCK]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[FV_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO

DROP INDEX [dbo].[STORE_EXTERNAL_INTRANSIT].STORE_EXTERNAL_INTRANSIT_ST_IDX
CREATE UNIQUE NONCLUSTERED INDEX [STORE_EXTERNAL_INTRANSIT_ST_IDX] ON [dbo].[STORE_EXTERNAL_INTRANSIT]
(
	[ST_RID] ASC,
	[HN_RID] ASC,
	[TIME_ID] ASC
)WITH (FILLFACTOR = 80) ON [PRIMARY]
GO