net stop MIDRetailControlService
net stop MIDRetailHierarchyService
net stop MIDRetailSchedulerService
net stop MIDRetailStoreService

cp MIDRetailControlService.exe.config.online MIDRetailControlService.exe.config

net start MIDRetailControlService
net start MIDRetailHierarchyService
net start MIDRetailSchedulerService
net start MIDRetailStoreService
net start MIDRetailJobService

