"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\installutil" /u "C:\Logility\RO\Control Service\MIDRetailControlService.exe"
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\installutil" /u "C:\Logility\RO\Scheduler Service\MIDRetailSchedulerService.exe"
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\installutil" /u "C:\Logility\RO\Store Service\MIDRetailStoreService.exe"
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\installutil" /u "C:\Logility\RO\Hierarchy Service\MIDRetailHierarchyService.exe"
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\installutil" /u "C:\Logility\RO\Job Service\MIDRetailJobService.exe"
