--dv =============================================
--dv Modified date: 2/7/2018
--dv Notes:	
--dv History: 
--dv =============================================    
CREATE TABLE [dbo].[Hierarchy_Data](
	[ID] [varchar](100) NULL,
	[NodeDisplay] [varchar](250) NULL,
	[ProductType] [varchar](50) NULL,
	[Hierarchy] [varchar](50) NULL,
	[Parent] [varchar](50) NULL,
	[Name] [varchar](50) NULL,
	[Description] [varchar](250) NULL
)

GO