--dv =============================================
--dv Modified date: 2/7/2018
--dv Notes:	
--dv History: 
--dv =============================================    
CREATE TABLE [dbo].[Stores_Data](
	[ID] [varchar](50) NOT NULL,
	[StoreDisplay] [varchar](200) NULL,
	[Name] [varchar](50) NULL,
	[Description] [varchar](50) NULL,
	[City] [varchar](50) NULL,
	[State] [varchar](50) NULL,
	[SellingSquareFeet] [varchar](50) NULL,
	[SellingOpenDate] [varchar](50) NULL,
	[SellingCloseDate] [varchar](50) NULL,
	[StockOpenDate] [varchar](50) NULL,
	[StockCloseDate] [varchar](50) NULL,
	[ActiveIndicator] [varchar](50) NULL,
	[Status] [varchar](50) NULL,
	[LeadTime] [varchar](50) NULL,
	[ShipDate] [varchar](50) NULL,
	[VSWID] [varchar](50) NULL
)

GO