//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClientsSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ClientsSchema.xsd", IsNullable=false)]
public partial class Clients {
    
    private ClientsClient[] clientField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Client")]
    public ClientsClient[] Client {
        get {
            return this.clientField;
        }
        set {
            this.clientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ClientsSchema.xsd")]
public partial class ClientsClient {
    
    private string nameField;
    
    private string prodVersionField;
    
    private string shipVersionField;
    
    private string calcLocationField;
    
    private string developmentBuildLocationField;
    
    private string qABuildLocationField;
    
    private string releaseLocationField;
    
    private string documentationMainlineField;
    
    private string documentationBranchField;
    
    private string fTPLocationField;
    
    private string releaseTypeField;
    
    private bool customReportsField;
    
    private bool allocationInstalledField;
    
    private bool planningInstalledField;
    
    private bool sizeInstalledField;
    
    private bool assortmentInstalledField;
    
    private bool groupAllocationInstalledField;
    
    private bool masterInstalledField;
    
    private bool shipAsISOField;
    
    private bool analyticsInstalledField;
	
    private bool notdaaField;
    
    private string valueField;
    
    public ClientsClient() {
        this.customReportsField = false;
        this.allocationInstalledField = true;
        this.planningInstalledField = true;
        this.sizeInstalledField = true;
        this.assortmentInstalledField = false;
        this.groupAllocationInstalledField = false;
        this.masterInstalledField = false;
        this.shipAsISOField = true;
        this.analyticsInstalledField = false;
        this.notdaaField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProdVersion {
        get {
            return this.prodVersionField;
        }
        set {
            this.prodVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ShipVersion {
        get {
            return this.shipVersionField;
        }
        set {
            this.shipVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CalcLocation {
        get {
            return this.calcLocationField;
        }
        set {
            this.calcLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DevelopmentBuildLocation {
        get {
            return this.developmentBuildLocationField;
        }
        set {
            this.developmentBuildLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string QABuildLocation {
        get {
            return this.qABuildLocationField;
        }
        set {
            this.qABuildLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReleaseLocation {
        get {
            return this.releaseLocationField;
        }
        set {
            this.releaseLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DocumentationMainline {
        get {
            return this.documentationMainlineField;
        }
        set {
            this.documentationMainlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DocumentationBranch {
        get {
            return this.documentationBranchField;
        }
        set {
            this.documentationBranchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FTPLocation {
        get {
            return this.fTPLocationField;
        }
        set {
            this.fTPLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReleaseType {
        get {
            return this.releaseTypeField;
        }
        set {
            this.releaseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool CustomReports {
        get {
            return this.customReportsField;
        }
        set {
            this.customReportsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool AllocationInstalled {
        get {
            return this.allocationInstalledField;
        }
        set {
            this.allocationInstalledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool PlanningInstalled {
        get {
            return this.planningInstalledField;
        }
        set {
            this.planningInstalledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool SizeInstalled {
        get {
            return this.sizeInstalledField;
        }
        set {
            this.sizeInstalledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool AssortmentInstalled {
        get {
            return this.assortmentInstalledField;
        }
        set {
            this.assortmentInstalledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool GroupAllocationInstalled {
        get {
            return this.groupAllocationInstalledField;
        }
        set {
            this.groupAllocationInstalledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool MasterInstalled {
        get {
            return this.masterInstalledField;
        }
        set {
            this.masterInstalledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool ShipAsISO {
        get {
            return this.shipAsISOField;
        }
        set {
            this.shipAsISOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool AnalyticsInstalled {
        get {
            return this.analyticsInstalledField;
        }
        set {
            this.analyticsInstalledField = value;
        }
    }
	
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Notdaa {
        get {
            return this.notdaaField;
        }
        set {
            this.notdaaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
