//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace MIDRetail.DataCommon.Schema
{
}

namespace MIDRetail.DataCommon.Schema
{
}

namespace MIDRetail.DataCommon.Schema
{
}

namespace MIDRetail.DataCommon.Schema
{
}

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ChainSetPercent {
    
    private ChainSetPercentLine[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ChainSetPercentLine[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ChainSetPercentLine {
    
    private string yearWeekField;
    
    private string nodeIdField;
    
    private string storeAttributeField;
    
    private string storeAttributeSetField;
    
    private string percentageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string yearWeek {
        get {
            return this.yearWeekField;
        }
        set {
            this.yearWeekField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodeId {
        get {
            return this.nodeIdField;
        }
        set {
            this.nodeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string storeAttribute {
        get {
            return this.storeAttributeField;
        }
        set {
            this.storeAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string storeAttributeSet {
        get {
            return this.storeAttributeSetField;
        }
        set {
            this.storeAttributeSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
}
