//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DailyPercentagesLoadSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DailyPercentagesLoadSchema.xsd", IsNullable=false)]
public partial class DailyPercentages {
    
    private DailyPercentagesProduct[] productField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Product")]
    public DailyPercentagesProduct[] Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DailyPercentagesLoadSchema.xsd")]
public partial class DailyPercentagesProduct {
    
    private DailyPercentagesProductStore[] storeField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Store")]
    public DailyPercentagesProductStore[] Store {
        get {
            return this.storeField;
        }
        set {
            this.storeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DailyPercentagesLoadSchema.xsd")]
public partial class DailyPercentagesProductStore {
    
    private DailyPercentagesProductStoreFiscalPeriod[] fiscalPeriodField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FiscalPeriod")]
    public DailyPercentagesProductStoreFiscalPeriod[] FiscalPeriod {
        get {
            return this.fiscalPeriodField;
        }
        set {
            this.fiscalPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DailyPercentagesLoadSchema.xsd")]
public partial class DailyPercentagesProductStoreFiscalPeriod {
    
    private string beginDateField;
    
    private string endDateField;
    
    private float day1Field;
    
    private float day2Field;
    
    private float day3Field;
    
    private float day4Field;
    
    private float day5Field;
    
    private float day6Field;
    
    private float day7Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BeginDate {
        get {
            return this.beginDateField;
        }
        set {
            this.beginDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EndDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Day1 {
        get {
            return this.day1Field;
        }
        set {
            this.day1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Day2 {
        get {
            return this.day2Field;
        }
        set {
            this.day2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Day3 {
        get {
            return this.day3Field;
        }
        set {
            this.day3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Day4 {
        get {
            return this.day4Field;
        }
        set {
            this.day4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Day5 {
        get {
            return this.day5Field;
        }
        set {
            this.day5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Day6 {
        get {
            return this.day6Field;
        }
        set {
            this.day6Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Day7 {
        get {
            return this.day7Field;
        }
        set {
            this.day7Field = value;
        }
    }
}
