//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/HeaderReleaseSchema.xsd", IsNullable=false)]
public partial class Releases {
    
    private ReleasesRelease[] releaseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Release")]
    public ReleasesRelease[] Release {
        get {
            return this.releaseField;
        }
        set {
            this.releaseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesRelease {
    
    private ReleasesReleaseCharacteristic[] characteristicField;
    
    private ReleasesReleasePack[] packField;
    
    private ReleasesReleaseBulkColor[] bulkColorField;
    
    private ReleasesReleaseTotal totalField;
    
    private string headerIdField;
    
    private string headerDescriptionField;
    
    private System.DateTime headerDateField;
    
    private bool headerDateFieldSpecified;
    
    private System.DateTime releaseDateField;
    
    private bool releaseDateFieldSpecified;
    
    private string userNameField;
    
    private double unitRetailField;
    
    private bool unitRetailFieldSpecified;
    
    private double unitCostField;
    
    private bool unitCostFieldSpecified;
    
    private int totalReceivedUnitsField;
    
    private bool totalReceivedUnitsFieldSpecified;
    
    private int totalAllocatedUnitsField;
    
    private bool totalAllocatedUnitsFieldSpecified;
    
    private int totalVSWAllocatedUnitsField;
    
    private bool totalVSWAllocatedUnitsFieldSpecified;
    
    private int totalReserveUnitsField;
    
    private bool totalReserveUnitsFieldSpecified;
    
    private string styleIdField;
    
    private string parentOfStyleIdField;
    
    private string sizeGroupNameField;
    
    private int bulkMultipleField;
    
    private bool bulkMultipleFieldSpecified;
    
    private string headerTypeField;
    
    private string distCenterField;
    
    private string vendorField;
    
    private string purchaseOrderField;
    
    private string notesField;
    
    private string masterField;
    
    private int allocatedUnitsField;
    
    private bool allocatedUnitsFieldSpecified;
    
    private int vSWAllocatedUnitsField;
    
    private bool vSWAllocatedUnitsFieldSpecified;
    
    private int origAllocatedUnitsField;
    
    private bool origAllocatedUnitsFieldSpecified;
    
    private int reserveUnitsField;
    
    private bool reserveUnitsFieldSpecified;
    
    private string vSWIDField;
    
    private string vSWProcessField;
    
    private string unitsPerCartonField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Characteristic")]
    public ReleasesReleaseCharacteristic[] Characteristic {
        get {
            return this.characteristicField;
        }
        set {
            this.characteristicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pack")]
    public ReleasesReleasePack[] Pack {
        get {
            return this.packField;
        }
        set {
            this.packField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BulkColor")]
    public ReleasesReleaseBulkColor[] BulkColor {
        get {
            return this.bulkColorField;
        }
        set {
            this.bulkColorField = value;
        }
    }
    
    /// <remarks/>
    public ReleasesReleaseTotal Total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string HeaderId {
        get {
            return this.headerIdField;
        }
        set {
            this.headerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string HeaderDescription {
        get {
            return this.headerDescriptionField;
        }
        set {
            this.headerDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime HeaderDate {
        get {
            return this.headerDateField;
        }
        set {
            this.headerDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HeaderDateSpecified {
        get {
            return this.headerDateFieldSpecified;
        }
        set {
            this.headerDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime ReleaseDate {
        get {
            return this.releaseDateField;
        }
        set {
            this.releaseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReleaseDateSpecified {
        get {
            return this.releaseDateFieldSpecified;
        }
        set {
            this.releaseDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double UnitRetail {
        get {
            return this.unitRetailField;
        }
        set {
            this.unitRetailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitRetailSpecified {
        get {
            return this.unitRetailFieldSpecified;
        }
        set {
            this.unitRetailFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double UnitCost {
        get {
            return this.unitCostField;
        }
        set {
            this.unitCostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitCostSpecified {
        get {
            return this.unitCostFieldSpecified;
        }
        set {
            this.unitCostFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int TotalReceivedUnits {
        get {
            return this.totalReceivedUnitsField;
        }
        set {
            this.totalReceivedUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalReceivedUnitsSpecified {
        get {
            return this.totalReceivedUnitsFieldSpecified;
        }
        set {
            this.totalReceivedUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int TotalAllocatedUnits {
        get {
            return this.totalAllocatedUnitsField;
        }
        set {
            this.totalAllocatedUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalAllocatedUnitsSpecified {
        get {
            return this.totalAllocatedUnitsFieldSpecified;
        }
        set {
            this.totalAllocatedUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int TotalVSWAllocatedUnits {
        get {
            return this.totalVSWAllocatedUnitsField;
        }
        set {
            this.totalVSWAllocatedUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalVSWAllocatedUnitsSpecified {
        get {
            return this.totalVSWAllocatedUnitsFieldSpecified;
        }
        set {
            this.totalVSWAllocatedUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int TotalReserveUnits {
        get {
            return this.totalReserveUnitsField;
        }
        set {
            this.totalReserveUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalReserveUnitsSpecified {
        get {
            return this.totalReserveUnitsFieldSpecified;
        }
        set {
            this.totalReserveUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StyleId {
        get {
            return this.styleIdField;
        }
        set {
            this.styleIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParentOfStyleId {
        get {
            return this.parentOfStyleIdField;
        }
        set {
            this.parentOfStyleIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeGroupName {
        get {
            return this.sizeGroupNameField;
        }
        set {
            this.sizeGroupNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int BulkMultiple {
        get {
            return this.bulkMultipleField;
        }
        set {
            this.bulkMultipleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BulkMultipleSpecified {
        get {
            return this.bulkMultipleFieldSpecified;
        }
        set {
            this.bulkMultipleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string HeaderType {
        get {
            return this.headerTypeField;
        }
        set {
            this.headerTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DistCenter {
        get {
            return this.distCenterField;
        }
        set {
            this.distCenterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Vendor {
        get {
            return this.vendorField;
        }
        set {
            this.vendorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PurchaseOrder {
        get {
            return this.purchaseOrderField;
        }
        set {
            this.purchaseOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Master {
        get {
            return this.masterField;
        }
        set {
            this.masterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int AllocatedUnits {
        get {
            return this.allocatedUnitsField;
        }
        set {
            this.allocatedUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AllocatedUnitsSpecified {
        get {
            return this.allocatedUnitsFieldSpecified;
        }
        set {
            this.allocatedUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int VSWAllocatedUnits {
        get {
            return this.vSWAllocatedUnitsField;
        }
        set {
            this.vSWAllocatedUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VSWAllocatedUnitsSpecified {
        get {
            return this.vSWAllocatedUnitsFieldSpecified;
        }
        set {
            this.vSWAllocatedUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int OrigAllocatedUnits {
        get {
            return this.origAllocatedUnitsField;
        }
        set {
            this.origAllocatedUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrigAllocatedUnitsSpecified {
        get {
            return this.origAllocatedUnitsFieldSpecified;
        }
        set {
            this.origAllocatedUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ReserveUnits {
        get {
            return this.reserveUnitsField;
        }
        set {
            this.reserveUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReserveUnitsSpecified {
        get {
            return this.reserveUnitsFieldSpecified;
        }
        set {
            this.reserveUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWID {
        get {
            return this.vSWIDField;
        }
        set {
            this.vSWIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWProcess {
        get {
            return this.vSWProcessField;
        }
        set {
            this.vSWProcessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UnitsPerCarton {
        get {
            return this.unitsPerCartonField;
        }
        set {
            this.unitsPerCartonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleaseCharacteristic {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleasePack {
    
    private ReleasesReleasePackPackStore[] packStoreField;
    
    private ReleasesReleasePackPackColor[] packColorField;
    
    private ReleasesReleasePackPackSize[] packSizeField;
    
    private string nameField;
    
    private int multipleField;
    
    private bool multipleFieldSpecified;
    
    private bool isGenericField;
    
    private bool isGenericFieldSpecified;
    
    private int packReceivedPacksField;
    
    private bool packReceivedPacksFieldSpecified;
    
    private int packAllocatedPacksField;
    
    private bool packAllocatedPacksFieldSpecified;
    
    private int packReservePacksField;
    
    private bool packReservePacksFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackStore")]
    public ReleasesReleasePackPackStore[] PackStore {
        get {
            return this.packStoreField;
        }
        set {
            this.packStoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackColor")]
    public ReleasesReleasePackPackColor[] PackColor {
        get {
            return this.packColorField;
        }
        set {
            this.packColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackSize")]
    public ReleasesReleasePackPackSize[] PackSize {
        get {
            return this.packSizeField;
        }
        set {
            this.packSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Multiple {
        get {
            return this.multipleField;
        }
        set {
            this.multipleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MultipleSpecified {
        get {
            return this.multipleFieldSpecified;
        }
        set {
            this.multipleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsGeneric {
        get {
            return this.isGenericField;
        }
        set {
            this.isGenericField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsGenericSpecified {
        get {
            return this.isGenericFieldSpecified;
        }
        set {
            this.isGenericFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PackReceivedPacks {
        get {
            return this.packReceivedPacksField;
        }
        set {
            this.packReceivedPacksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PackReceivedPacksSpecified {
        get {
            return this.packReceivedPacksFieldSpecified;
        }
        set {
            this.packReceivedPacksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PackAllocatedPacks {
        get {
            return this.packAllocatedPacksField;
        }
        set {
            this.packAllocatedPacksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PackAllocatedPacksSpecified {
        get {
            return this.packAllocatedPacksFieldSpecified;
        }
        set {
            this.packAllocatedPacksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PackReservePacks {
        get {
            return this.packReservePacksField;
        }
        set {
            this.packReservePacksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PackReservePacksSpecified {
        get {
            return this.packReservePacksFieldSpecified;
        }
        set {
            this.packReservePacksFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleasePackPackStore {
    
    private string storeIDField;
    
    private int packsField;
    
    private bool packsFieldSpecified;
    
    private string vSWIDField;
    
    private int vSWPacksField;
    
    private bool vSWPacksFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreID {
        get {
            return this.storeIDField;
        }
        set {
            this.storeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Packs {
        get {
            return this.packsField;
        }
        set {
            this.packsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PacksSpecified {
        get {
            return this.packsFieldSpecified;
        }
        set {
            this.packsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWID {
        get {
            return this.vSWIDField;
        }
        set {
            this.vSWIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int VSWPacks {
        get {
            return this.vSWPacksField;
        }
        set {
            this.vSWPacksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VSWPacksSpecified {
        get {
            return this.vSWPacksFieldSpecified;
        }
        set {
            this.vSWPacksFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleasePackPackColor {
    
    private ReleasesReleasePackPackColorPackColorStore[] packColorStoreField;
    
    private ReleasesReleasePackPackColorPackColorSize[] packColorSizeField;
    
    private string colorCodeIDField;
    
    private string colorCodeNameField;
    
    private string colorCodeDescriptionField;
    
    private int colorUnitsField;
    
    private bool colorUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackColorStore")]
    public ReleasesReleasePackPackColorPackColorStore[] PackColorStore {
        get {
            return this.packColorStoreField;
        }
        set {
            this.packColorStoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackColorSize")]
    public ReleasesReleasePackPackColorPackColorSize[] PackColorSize {
        get {
            return this.packColorSizeField;
        }
        set {
            this.packColorSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeID {
        get {
            return this.colorCodeIDField;
        }
        set {
            this.colorCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeName {
        get {
            return this.colorCodeNameField;
        }
        set {
            this.colorCodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeDescription {
        get {
            return this.colorCodeDescriptionField;
        }
        set {
            this.colorCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ColorUnits {
        get {
            return this.colorUnitsField;
        }
        set {
            this.colorUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColorUnitsSpecified {
        get {
            return this.colorUnitsFieldSpecified;
        }
        set {
            this.colorUnitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleasePackPackColorPackColorStore {
    
    private string storeIDField;
    
    private int unitsField;
    
    private bool unitsFieldSpecified;
    
    private string vSWIDField;
    
    private int vSWUnitsField;
    
    private bool vSWUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreID {
        get {
            return this.storeIDField;
        }
        set {
            this.storeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWID {
        get {
            return this.vSWIDField;
        }
        set {
            this.vSWIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int VSWUnits {
        get {
            return this.vSWUnitsField;
        }
        set {
            this.vSWUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VSWUnitsSpecified {
        get {
            return this.vSWUnitsFieldSpecified;
        }
        set {
            this.vSWUnitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleasePackPackColorPackColorSize {
    
    private ReleasesReleasePackPackColorPackColorSizePackColorSizeStore[] packColorSizeStoreField;
    
    private string sizeCodeIDField;
    
    private string sizeCodeNameField;
    
    private string sizeCodeDescriptionField;
    
    private string sizeCodePrimaryField;
    
    private string sizeCodeSecondaryField;
    
    private string sizeCodeProductCategoryField;
    
    private int sizeUnitsField;
    
    private bool sizeUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackColorSizeStore")]
    public ReleasesReleasePackPackColorPackColorSizePackColorSizeStore[] PackColorSizeStore {
        get {
            return this.packColorSizeStoreField;
        }
        set {
            this.packColorSizeStoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeID {
        get {
            return this.sizeCodeIDField;
        }
        set {
            this.sizeCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeName {
        get {
            return this.sizeCodeNameField;
        }
        set {
            this.sizeCodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeDescription {
        get {
            return this.sizeCodeDescriptionField;
        }
        set {
            this.sizeCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodePrimary {
        get {
            return this.sizeCodePrimaryField;
        }
        set {
            this.sizeCodePrimaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeSecondary {
        get {
            return this.sizeCodeSecondaryField;
        }
        set {
            this.sizeCodeSecondaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeProductCategory {
        get {
            return this.sizeCodeProductCategoryField;
        }
        set {
            this.sizeCodeProductCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SizeUnits {
        get {
            return this.sizeUnitsField;
        }
        set {
            this.sizeUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeUnitsSpecified {
        get {
            return this.sizeUnitsFieldSpecified;
        }
        set {
            this.sizeUnitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleasePackPackColorPackColorSizePackColorSizeStore {
    
    private string storeIDField;
    
    private int unitsField;
    
    private bool unitsFieldSpecified;
    
    private string vSWIDField;
    
    private int vSWUnitsField;
    
    private bool vSWUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreID {
        get {
            return this.storeIDField;
        }
        set {
            this.storeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWID {
        get {
            return this.vSWIDField;
        }
        set {
            this.vSWIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int VSWUnits {
        get {
            return this.vSWUnitsField;
        }
        set {
            this.vSWUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VSWUnitsSpecified {
        get {
            return this.vSWUnitsFieldSpecified;
        }
        set {
            this.vSWUnitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleasePackPackSize {
    
    private ReleasesReleasePackPackSizePackSizeStore[] packSizeStoreField;
    
    private string sizeCodeIDField;
    
    private string sizeCodeNameField;
    
    private string sizeCodeDescriptionField;
    
    private string sizeCodePrimaryField;
    
    private string sizeCodeSecondaryField;
    
    private string sizeCodeProductCategoryField;
    
    private int sizeUnitsField;
    
    private bool sizeUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackSizeStore")]
    public ReleasesReleasePackPackSizePackSizeStore[] PackSizeStore {
        get {
            return this.packSizeStoreField;
        }
        set {
            this.packSizeStoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeID {
        get {
            return this.sizeCodeIDField;
        }
        set {
            this.sizeCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeName {
        get {
            return this.sizeCodeNameField;
        }
        set {
            this.sizeCodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeDescription {
        get {
            return this.sizeCodeDescriptionField;
        }
        set {
            this.sizeCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodePrimary {
        get {
            return this.sizeCodePrimaryField;
        }
        set {
            this.sizeCodePrimaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeSecondary {
        get {
            return this.sizeCodeSecondaryField;
        }
        set {
            this.sizeCodeSecondaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeProductCategory {
        get {
            return this.sizeCodeProductCategoryField;
        }
        set {
            this.sizeCodeProductCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SizeUnits {
        get {
            return this.sizeUnitsField;
        }
        set {
            this.sizeUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeUnitsSpecified {
        get {
            return this.sizeUnitsFieldSpecified;
        }
        set {
            this.sizeUnitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleasePackPackSizePackSizeStore {
    
    private string storeIDField;
    
    private int unitsField;
    
    private bool unitsFieldSpecified;
    
    private string vSWIDField;
    
    private int vSWUnitsField;
    
    private bool vSWUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreID {
        get {
            return this.storeIDField;
        }
        set {
            this.storeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWID {
        get {
            return this.vSWIDField;
        }
        set {
            this.vSWIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int VSWUnits {
        get {
            return this.vSWUnitsField;
        }
        set {
            this.vSWUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VSWUnitsSpecified {
        get {
            return this.vSWUnitsFieldSpecified;
        }
        set {
            this.vSWUnitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleaseBulkColor {
    
    private ReleasesReleaseBulkColorBulkColorStore[] bulkColorStoreField;
    
    private ReleasesReleaseBulkColorBulkColorSize[] bulkColorSizeField;
    
    private string colorCodeIDField;
    
    private string colorCodeNameField;
    
    private string colorCodeDescriptionField;
    
    private int colorReceivedUnitsField;
    
    private bool colorReceivedUnitsFieldSpecified;
    
    private int colorAllocatedUnitsField;
    
    private bool colorAllocatedUnitsFieldSpecified;
    
    private int colorReserveUnitsField;
    
    private bool colorReserveUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BulkColorStore")]
    public ReleasesReleaseBulkColorBulkColorStore[] BulkColorStore {
        get {
            return this.bulkColorStoreField;
        }
        set {
            this.bulkColorStoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BulkColorSize")]
    public ReleasesReleaseBulkColorBulkColorSize[] BulkColorSize {
        get {
            return this.bulkColorSizeField;
        }
        set {
            this.bulkColorSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeID {
        get {
            return this.colorCodeIDField;
        }
        set {
            this.colorCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeName {
        get {
            return this.colorCodeNameField;
        }
        set {
            this.colorCodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeDescription {
        get {
            return this.colorCodeDescriptionField;
        }
        set {
            this.colorCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ColorReceivedUnits {
        get {
            return this.colorReceivedUnitsField;
        }
        set {
            this.colorReceivedUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColorReceivedUnitsSpecified {
        get {
            return this.colorReceivedUnitsFieldSpecified;
        }
        set {
            this.colorReceivedUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ColorAllocatedUnits {
        get {
            return this.colorAllocatedUnitsField;
        }
        set {
            this.colorAllocatedUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColorAllocatedUnitsSpecified {
        get {
            return this.colorAllocatedUnitsFieldSpecified;
        }
        set {
            this.colorAllocatedUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ColorReserveUnits {
        get {
            return this.colorReserveUnitsField;
        }
        set {
            this.colorReserveUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColorReserveUnitsSpecified {
        get {
            return this.colorReserveUnitsFieldSpecified;
        }
        set {
            this.colorReserveUnitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleaseBulkColorBulkColorStore {
    
    private string storeIDField;
    
    private int unitsField;
    
    private bool unitsFieldSpecified;
    
    private string vSWIDField;
    
    private int vSWUnitsField;
    
    private bool vSWUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreID {
        get {
            return this.storeIDField;
        }
        set {
            this.storeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWID {
        get {
            return this.vSWIDField;
        }
        set {
            this.vSWIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int VSWUnits {
        get {
            return this.vSWUnitsField;
        }
        set {
            this.vSWUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VSWUnitsSpecified {
        get {
            return this.vSWUnitsFieldSpecified;
        }
        set {
            this.vSWUnitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleaseBulkColorBulkColorSize {
    
    private ReleasesReleaseBulkColorBulkColorSizeBulkColorSizeStore[] bulkColorSizeStoreField;
    
    private string sizeCodeIDField;
    
    private string sizeCodeNameField;
    
    private string sizeCodeDescriptionField;
    
    private string sizeCodePrimaryField;
    
    private string sizeCodeSecondaryField;
    
    private string sizeCodeProductCategoryField;
    
    private int sizeReceivedUnitsField;
    
    private bool sizeReceivedUnitsFieldSpecified;
    
    private int sizeAllocatedUnitsField;
    
    private bool sizeAllocatedUnitsFieldSpecified;
    
    private int sizeReserveUnitsField;
    
    private bool sizeReserveUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BulkColorSizeStore")]
    public ReleasesReleaseBulkColorBulkColorSizeBulkColorSizeStore[] BulkColorSizeStore {
        get {
            return this.bulkColorSizeStoreField;
        }
        set {
            this.bulkColorSizeStoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeID {
        get {
            return this.sizeCodeIDField;
        }
        set {
            this.sizeCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeName {
        get {
            return this.sizeCodeNameField;
        }
        set {
            this.sizeCodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeDescription {
        get {
            return this.sizeCodeDescriptionField;
        }
        set {
            this.sizeCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodePrimary {
        get {
            return this.sizeCodePrimaryField;
        }
        set {
            this.sizeCodePrimaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeSecondary {
        get {
            return this.sizeCodeSecondaryField;
        }
        set {
            this.sizeCodeSecondaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeProductCategory {
        get {
            return this.sizeCodeProductCategoryField;
        }
        set {
            this.sizeCodeProductCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SizeReceivedUnits {
        get {
            return this.sizeReceivedUnitsField;
        }
        set {
            this.sizeReceivedUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeReceivedUnitsSpecified {
        get {
            return this.sizeReceivedUnitsFieldSpecified;
        }
        set {
            this.sizeReceivedUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SizeAllocatedUnits {
        get {
            return this.sizeAllocatedUnitsField;
        }
        set {
            this.sizeAllocatedUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeAllocatedUnitsSpecified {
        get {
            return this.sizeAllocatedUnitsFieldSpecified;
        }
        set {
            this.sizeAllocatedUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SizeReserveUnits {
        get {
            return this.sizeReserveUnitsField;
        }
        set {
            this.sizeReserveUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeReserveUnitsSpecified {
        get {
            return this.sizeReserveUnitsFieldSpecified;
        }
        set {
            this.sizeReserveUnitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleaseBulkColorBulkColorSizeBulkColorSizeStore {
    
    private string storeIDField;
    
    private int unitsField;
    
    private bool unitsFieldSpecified;
    
    private string vSWIDField;
    
    private int vSWUnitsField;
    
    private bool vSWUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreID {
        get {
            return this.storeIDField;
        }
        set {
            this.storeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWID {
        get {
            return this.vSWIDField;
        }
        set {
            this.vSWIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int VSWUnits {
        get {
            return this.vSWUnitsField;
        }
        set {
            this.vSWUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VSWUnitsSpecified {
        get {
            return this.vSWUnitsFieldSpecified;
        }
        set {
            this.vSWUnitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleaseTotal {
    
    private ReleasesReleaseTotalTotalStore[] totalStoreField;
    
    private int multipleField;
    
    private bool multipleFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TotalStore")]
    public ReleasesReleaseTotalTotalStore[] TotalStore {
        get {
            return this.totalStoreField;
        }
        set {
            this.totalStoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Multiple {
        get {
            return this.multipleField;
        }
        set {
            this.multipleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MultipleSpecified {
        get {
            return this.multipleFieldSpecified;
        }
        set {
            this.multipleFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderReleaseSchema.xsd")]
public partial class ReleasesReleaseTotalTotalStore {
    
    private string storeIDField;
    
    private int unitsField;
    
    private bool unitsFieldSpecified;
    
    private string vSWIDField;
    
    private int vSWUnitsField;
    
    private bool vSWUnitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreID {
        get {
            return this.storeIDField;
        }
        set {
            this.storeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWID {
        get {
            return this.vSWIDField;
        }
        set {
            this.vSWIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int VSWUnits {
        get {
            return this.vSWUnitsField;
        }
        set {
            this.vSWUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VSWUnitsSpecified {
        get {
            return this.vSWUnitsFieldSpecified;
        }
        set {
            this.vSWUnitsFieldSpecified = value;
        }
    }
}
