//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/HeaderLoadStatusSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/HeaderLoadStatusSchema.xsd", IsNullable=false)]
public class HeaderLoadStatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HeaderStatus")]
    public HeaderLoadStatusHeaderStatus[] HeaderStatus;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/HeaderLoadStatusSchema.xsd")]
public class HeaderLoadStatusHeaderStatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string HeaderId;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool LoadStatus;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LoadStatusSpecified;
}
