//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/HeaderLoadSchema.xsd", IsNullable=false)]
public partial class Headers {
    
    private HeadersOptions optionsField;
    
    private HeadersHeader[] headerField;
    
    /// <remarks/>
    public HeadersOptions Options {
        get {
            return this.optionsField;
        }
        set {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Header")]
    public HeadersHeader[] Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public partial class HeadersOptions {
    
    private bool autoAddCharacteristicsField;
    
    private bool autoAddCharacteristicsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool AutoAddCharacteristics {
        get {
            return this.autoAddCharacteristicsField;
        }
        set {
            this.autoAddCharacteristicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AutoAddCharacteristicsSpecified {
        get {
            return this.autoAddCharacteristicsFieldSpecified;
        }
        set {
            this.autoAddCharacteristicsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public partial class HeadersHeader {
    
    private HeadersHeaderBulkColor[] bulkColorField;
    
    private HeadersHeaderPack[] packField;
    
    private HeadersHeaderCharacteristic[] characteristicField;
    
    private HeadersHeaderMethod[] methodsField;
    
    private string headerIdField;
    
    private string newHeaderIdField;
    
    private HeadersHeaderHeaderAction headerActionField;
    
    private bool headerActionFieldSpecified;
    
    private string headerDescriptionField;
    
    private System.DateTime headerDateField;
    
    private bool headerDateFieldSpecified;
    
    private double unitRetailField;
    
    private bool unitRetailFieldSpecified;
    
    private double unitCostField;
    
    private bool unitCostFieldSpecified;
    
    private int totalUnitsField;
    
    private bool totalUnitsFieldSpecified;
    
    private string styleIdField;
    
    private string parentOfStyleIdField;
    
    private string sizeGroupNameField;
    
    private int bulkMultipleField;
    
    private bool bulkMultipleFieldSpecified;
    
    private HeadersHeaderHeaderType headerTypeField;
    
    private bool headerTypeFieldSpecified;
    
    private string distCenterField;
    
    private string vendorField;
    
    private string purchaseOrderField;
    
    private string workflowField;
    
    private bool workflowTriggerField;
    
    private bool workflowTriggerFieldSpecified;
    
    private string notesField;
    
    private string styleNameField;
    
    private string vSWIDField;
    
    private HeadersHeaderVSWProcess vSWProcessField;
    
    private string unitsPerCartonField;
    
    public HeadersHeader() {
        this.vSWProcessField = HeadersHeaderVSWProcess.Replace;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BulkColor")]
    public HeadersHeaderBulkColor[] BulkColor {
        get {
            return this.bulkColorField;
        }
        set {
            this.bulkColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Pack")]
    public HeadersHeaderPack[] Pack {
        get {
            return this.packField;
        }
        set {
            this.packField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Characteristic")]
    public HeadersHeaderCharacteristic[] Characteristic {
        get {
            return this.characteristicField;
        }
        set {
            this.characteristicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Method", IsNullable=false)]
    public HeadersHeaderMethod[] Methods {
        get {
            return this.methodsField;
        }
        set {
            this.methodsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string HeaderId {
        get {
            return this.headerIdField;
        }
        set {
            this.headerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NewHeaderId {
        get {
            return this.newHeaderIdField;
        }
        set {
            this.newHeaderIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public HeadersHeaderHeaderAction HeaderAction {
        get {
            return this.headerActionField;
        }
        set {
            this.headerActionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HeaderActionSpecified {
        get {
            return this.headerActionFieldSpecified;
        }
        set {
            this.headerActionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string HeaderDescription {
        get {
            return this.headerDescriptionField;
        }
        set {
            this.headerDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime HeaderDate {
        get {
            return this.headerDateField;
        }
        set {
            this.headerDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HeaderDateSpecified {
        get {
            return this.headerDateFieldSpecified;
        }
        set {
            this.headerDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double UnitRetail {
        get {
            return this.unitRetailField;
        }
        set {
            this.unitRetailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitRetailSpecified {
        get {
            return this.unitRetailFieldSpecified;
        }
        set {
            this.unitRetailFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double UnitCost {
        get {
            return this.unitCostField;
        }
        set {
            this.unitCostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitCostSpecified {
        get {
            return this.unitCostFieldSpecified;
        }
        set {
            this.unitCostFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int TotalUnits {
        get {
            return this.totalUnitsField;
        }
        set {
            this.totalUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalUnitsSpecified {
        get {
            return this.totalUnitsFieldSpecified;
        }
        set {
            this.totalUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StyleId {
        get {
            return this.styleIdField;
        }
        set {
            this.styleIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParentOfStyleId {
        get {
            return this.parentOfStyleIdField;
        }
        set {
            this.parentOfStyleIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeGroupName {
        get {
            return this.sizeGroupNameField;
        }
        set {
            this.sizeGroupNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int BulkMultiple {
        get {
            return this.bulkMultipleField;
        }
        set {
            this.bulkMultipleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BulkMultipleSpecified {
        get {
            return this.bulkMultipleFieldSpecified;
        }
        set {
            this.bulkMultipleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public HeadersHeaderHeaderType HeaderType {
        get {
            return this.headerTypeField;
        }
        set {
            this.headerTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HeaderTypeSpecified {
        get {
            return this.headerTypeFieldSpecified;
        }
        set {
            this.headerTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DistCenter {
        get {
            return this.distCenterField;
        }
        set {
            this.distCenterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Vendor {
        get {
            return this.vendorField;
        }
        set {
            this.vendorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PurchaseOrder {
        get {
            return this.purchaseOrderField;
        }
        set {
            this.purchaseOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Workflow {
        get {
            return this.workflowField;
        }
        set {
            this.workflowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool WorkflowTrigger {
        get {
            return this.workflowTriggerField;
        }
        set {
            this.workflowTriggerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WorkflowTriggerSpecified {
        get {
            return this.workflowTriggerFieldSpecified;
        }
        set {
            this.workflowTriggerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StyleName {
        get {
            return this.styleNameField;
        }
        set {
            this.styleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWID {
        get {
            return this.vSWIDField;
        }
        set {
            this.vSWIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(HeadersHeaderVSWProcess.Replace)]
    public HeadersHeaderVSWProcess VSWProcess {
        get {
            return this.vSWProcessField;
        }
        set {
            this.vSWProcessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UnitsPerCarton {
        get {
            return this.unitsPerCartonField;
        }
        set {
            this.unitsPerCartonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public partial class HeadersHeaderBulkColor {
    
    private HeadersHeaderBulkColorBulkColorSize[] bulkColorSizeField;
    
    private string colorCodeIDField;
    
    private string colorCodeNameField;
    
    private string colorCodeDescriptionField;
    
    private string colorCodeGroupField;
    
    private int unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BulkColorSize")]
    public HeadersHeaderBulkColorBulkColorSize[] BulkColorSize {
        get {
            return this.bulkColorSizeField;
        }
        set {
            this.bulkColorSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeID {
        get {
            return this.colorCodeIDField;
        }
        set {
            this.colorCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeName {
        get {
            return this.colorCodeNameField;
        }
        set {
            this.colorCodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeDescription {
        get {
            return this.colorCodeDescriptionField;
        }
        set {
            this.colorCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeGroup {
        get {
            return this.colorCodeGroupField;
        }
        set {
            this.colorCodeGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public partial class HeadersHeaderBulkColorBulkColorSize {
    
    private string sizeCodeIDField;
    
    private string sizeCodeNameField;
    
    private string sizeCodeDescriptionField;
    
    private string sizeCodePrimaryField;
    
    private string sizeCodeSecondaryField;
    
    private string sizeCodeProductCategoryField;
    
    private int unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeID {
        get {
            return this.sizeCodeIDField;
        }
        set {
            this.sizeCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeName {
        get {
            return this.sizeCodeNameField;
        }
        set {
            this.sizeCodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeDescription {
        get {
            return this.sizeCodeDescriptionField;
        }
        set {
            this.sizeCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodePrimary {
        get {
            return this.sizeCodePrimaryField;
        }
        set {
            this.sizeCodePrimaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeSecondary {
        get {
            return this.sizeCodeSecondaryField;
        }
        set {
            this.sizeCodeSecondaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeProductCategory {
        get {
            return this.sizeCodeProductCategoryField;
        }
        set {
            this.sizeCodeProductCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public partial class HeadersHeaderPack {
    
    private HeadersHeaderPackPackColor[] packColorField;
    
    private HeadersHeaderPackPackSize[] packSizeField;
    
    private string nameField;
    
    private int packsField;
    
    private int multipleField;
    
    private bool isGenericField;
    
    private bool isGenericFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackColor")]
    public HeadersHeaderPackPackColor[] PackColor {
        get {
            return this.packColorField;
        }
        set {
            this.packColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackSize")]
    public HeadersHeaderPackPackSize[] PackSize {
        get {
            return this.packSizeField;
        }
        set {
            this.packSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Packs {
        get {
            return this.packsField;
        }
        set {
            this.packsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Multiple {
        get {
            return this.multipleField;
        }
        set {
            this.multipleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsGeneric {
        get {
            return this.isGenericField;
        }
        set {
            this.isGenericField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsGenericSpecified {
        get {
            return this.isGenericFieldSpecified;
        }
        set {
            this.isGenericFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public partial class HeadersHeaderPackPackColor {
    
    private HeadersHeaderPackPackColorPackColorSize[] packColorSizeField;
    
    private string colorCodeIDField;
    
    private string colorCodeNameField;
    
    private string colorCodeDescriptionField;
    
    private string colorCodeGroupField;
    
    private int unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PackColorSize")]
    public HeadersHeaderPackPackColorPackColorSize[] PackColorSize {
        get {
            return this.packColorSizeField;
        }
        set {
            this.packColorSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeID {
        get {
            return this.colorCodeIDField;
        }
        set {
            this.colorCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeName {
        get {
            return this.colorCodeNameField;
        }
        set {
            this.colorCodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeDescription {
        get {
            return this.colorCodeDescriptionField;
        }
        set {
            this.colorCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCodeGroup {
        get {
            return this.colorCodeGroupField;
        }
        set {
            this.colorCodeGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public partial class HeadersHeaderPackPackColorPackColorSize {
    
    private string sizeCodeIDField;
    
    private string sizeCodeNameField;
    
    private string sizeCodeDescriptionField;
    
    private string sizeCodePrimaryField;
    
    private string sizeCodeSecondaryField;
    
    private string sizeCodeProductCategoryField;
    
    private int unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeID {
        get {
            return this.sizeCodeIDField;
        }
        set {
            this.sizeCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeName {
        get {
            return this.sizeCodeNameField;
        }
        set {
            this.sizeCodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeDescription {
        get {
            return this.sizeCodeDescriptionField;
        }
        set {
            this.sizeCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodePrimary {
        get {
            return this.sizeCodePrimaryField;
        }
        set {
            this.sizeCodePrimaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeSecondary {
        get {
            return this.sizeCodeSecondaryField;
        }
        set {
            this.sizeCodeSecondaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeProductCategory {
        get {
            return this.sizeCodeProductCategoryField;
        }
        set {
            this.sizeCodeProductCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public partial class HeadersHeaderPackPackSize {
    
    private string sizeCodeIDField;
    
    private string sizeCodeNameField;
    
    private string sizeCodeDescriptionField;
    
    private string sizeCodePrimaryField;
    
    private string sizeCodeSecondaryField;
    
    private string sizeCodeProductCategoryField;
    
    private int unitsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeID {
        get {
            return this.sizeCodeIDField;
        }
        set {
            this.sizeCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeName {
        get {
            return this.sizeCodeNameField;
        }
        set {
            this.sizeCodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeDescription {
        get {
            return this.sizeCodeDescriptionField;
        }
        set {
            this.sizeCodeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodePrimary {
        get {
            return this.sizeCodePrimaryField;
        }
        set {
            this.sizeCodePrimaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeSecondary {
        get {
            return this.sizeCodeSecondaryField;
        }
        set {
            this.sizeCodeSecondaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeProductCategory {
        get {
            return this.sizeCodeProductCategoryField;
        }
        set {
            this.sizeCodeProductCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public partial class HeadersHeaderCharacteristic {
    
    private string nameField;
    
    private string valueField;
    
    private bool protectField;
    
    private HeadersHeaderCharacteristicCharType charTypeField;
    
    public HeadersHeaderCharacteristic() {
        this.protectField = true;
        this.charTypeField = HeadersHeaderCharacteristicCharType.Unknown;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool Protect {
        get {
            return this.protectField;
        }
        set {
            this.protectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(HeadersHeaderCharacteristicCharType.Unknown)]
    public HeadersHeaderCharacteristicCharType CharType {
        get {
            return this.charTypeField;
        }
        set {
            this.charTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public enum HeadersHeaderCharacteristicCharType {
    
    /// <remarks/>
    Text,
    
    /// <remarks/>
    Date,
    
    /// <remarks/>
    Number,
    
    /// <remarks/>
    Dollar,
    
    /// <remarks/>
    Unknown,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public partial class HeadersHeaderMethod {
    
    private HeadersHeaderMethodType typeField;
    
    private bool typeFieldSpecified;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public HeadersHeaderMethodType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public enum HeadersHeaderMethodType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("General Allocation")]
    GeneralAllocation,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Allocation Override")]
    AllocationOverride,
    
    /// <remarks/>
    Rule,
    
    /// <remarks/>
    Velocity,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Fill Sizes")]
    FillSizes,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Basis Size")]
    BasisSize,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Size Need")]
    SizeNeed,
    
    /// <remarks/>
    Action,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public enum HeadersHeaderHeaderAction {
    
    /// <remarks/>
    Create,
    
    /// <remarks/>
    Modify,
    
    /// <remarks/>
    Remove,
    
    /// <remarks/>
    Reset,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public enum HeadersHeaderHeaderType {
    
    /// <remarks/>
    Receipt,
    
    /// <remarks/>
    PO,
    
    /// <remarks/>
    ASN,
    
    /// <remarks/>
    Dummy,
    
    /// <remarks/>
    DropShip,
    
    /// <remarks/>
    Reserve,
    
    /// <remarks/>
    WorkupTotalBuy,
    
    /// <remarks/>
    VSW,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HeaderLoadSchema.xsd")]
public enum HeadersHeaderVSWProcess {
    
    /// <remarks/>
    Adjust,
    
    /// <remarks/>
    Replace,
}
