//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/HierarchyLoadSchema.xsd", IsNullable=false)]
public partial class Hierarchies {
    
    private HierarchiesOptions optionsField;
    
    private HierarchiesHierarchy[] hierarchyField;
    
    /// <remarks/>
    public HierarchiesOptions Options {
        get {
            return this.optionsField;
        }
        set {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Hierarchy")]
    public HierarchiesHierarchy[] Hierarchy {
        get {
            return this.hierarchyField;
        }
        set {
            this.hierarchyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public partial class HierarchiesOptions {
    
    private HierarchiesOptionsReclassForecastVersion[] reclassForecastVersionField;
    
    private bool rollExternalIntransitField;
    
    private bool rollAlternateHierarchiesField;
    
    private bool reclassPreviewField;
    
    private bool autoAddCharacteristicsField;
    
    private bool autoAddCharacteristicsFieldSpecified;
    
    private bool allowDeletesField;
    
    private bool allowDeletesFieldSpecified;
    
    public HierarchiesOptions() {
        this.rollExternalIntransitField = false;
        this.rollAlternateHierarchiesField = false;
        this.reclassPreviewField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReclassForecastVersion")]
    public HierarchiesOptionsReclassForecastVersion[] ReclassForecastVersion {
        get {
            return this.reclassForecastVersionField;
        }
        set {
            this.reclassForecastVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool RollExternalIntransit {
        get {
            return this.rollExternalIntransitField;
        }
        set {
            this.rollExternalIntransitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool RollAlternateHierarchies {
        get {
            return this.rollAlternateHierarchiesField;
        }
        set {
            this.rollAlternateHierarchiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ReclassPreview {
        get {
            return this.reclassPreviewField;
        }
        set {
            this.reclassPreviewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool AutoAddCharacteristics {
        get {
            return this.autoAddCharacteristicsField;
        }
        set {
            this.autoAddCharacteristicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AutoAddCharacteristicsSpecified {
        get {
            return this.autoAddCharacteristicsFieldSpecified;
        }
        set {
            this.autoAddCharacteristicsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool AllowDeletes {
        get {
            return this.allowDeletesField;
        }
        set {
            this.allowDeletesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AllowDeletesSpecified {
        get {
            return this.allowDeletesFieldSpecified;
        }
        set {
            this.allowDeletesFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public partial class HierarchiesOptionsReclassForecastVersion {
    
    private string nameField;
    
    private bool rollupField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Rollup {
        get {
            return this.rollupField;
        }
        set {
            this.rollupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public partial class HierarchiesHierarchy {
    
    private HierarchiesHierarchyLevel[] levelField;
    
    private HierarchiesHierarchyProduct[] productField;
    
    private string idField;
    
    private bool updateDefinitionField;
    
    private HierarchiesHierarchyType typeField;
    
    private string colorField;
    
    public HierarchiesHierarchy() {
        this.updateDefinitionField = false;
        this.typeField = HierarchiesHierarchyType.Open;
        this.colorField = "default";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Level")]
    public HierarchiesHierarchyLevel[] Level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Product")]
    public HierarchiesHierarchyProduct[] Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool UpdateDefinition {
        get {
            return this.updateDefinitionField;
        }
        set {
            this.updateDefinitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(HierarchiesHierarchyType.Open)]
    public HierarchiesHierarchyType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("default")]
    public string Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public partial class HierarchiesHierarchyLevel {
    
    private string nameField;
    
    private HierarchiesHierarchyLevelType typeField;
    
    private HierarchiesHierarchyLevelPlanLevelType planLevelTypeField;
    
    private HierarchiesHierarchyLevelLengthType lengthTypeField;
    
    private int requiredSizeField;
    
    private int sizeRangeFromField;
    
    private int sizeRangeToField;
    
    private string colorField;
    
    private bool isOTSForecastLevelField;
    
    public HierarchiesHierarchyLevel() {
        this.typeField = HierarchiesHierarchyLevelType.Undefined;
        this.planLevelTypeField = HierarchiesHierarchyLevelPlanLevelType.Undefined;
        this.lengthTypeField = HierarchiesHierarchyLevelLengthType.Unrestricted;
        this.requiredSizeField = 0;
        this.sizeRangeFromField = 0;
        this.sizeRangeToField = 0;
        this.colorField = "default";
        this.isOTSForecastLevelField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(HierarchiesHierarchyLevelType.Undefined)]
    public HierarchiesHierarchyLevelType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(HierarchiesHierarchyLevelPlanLevelType.Undefined)]
    public HierarchiesHierarchyLevelPlanLevelType PlanLevelType {
        get {
            return this.planLevelTypeField;
        }
        set {
            this.planLevelTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(HierarchiesHierarchyLevelLengthType.Unrestricted)]
    public HierarchiesHierarchyLevelLengthType LengthType {
        get {
            return this.lengthTypeField;
        }
        set {
            this.lengthTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int RequiredSize {
        get {
            return this.requiredSizeField;
        }
        set {
            this.requiredSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int SizeRangeFrom {
        get {
            return this.sizeRangeFromField;
        }
        set {
            this.sizeRangeFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int SizeRangeTo {
        get {
            return this.sizeRangeToField;
        }
        set {
            this.sizeRangeToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("default")]
    public string Color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool IsOTSForecastLevel {
        get {
            return this.isOTSForecastLevelField;
        }
        set {
            this.isOTSForecastLevelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public enum HierarchiesHierarchyLevelType {
    
    /// <remarks/>
    Undefined,
    
    /// <remarks/>
    Style,
    
    /// <remarks/>
    Color,
    
    /// <remarks/>
    Size,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public enum HierarchiesHierarchyLevelPlanLevelType {
    
    /// <remarks/>
    Undefined,
    
    /// <remarks/>
    Regular,
    
    /// <remarks/>
    Total,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public enum HierarchiesHierarchyLevelLengthType {
    
    /// <remarks/>
    Unrestricted,
    
    /// <remarks/>
    Required,
    
    /// <remarks/>
    Range,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public partial class HierarchiesHierarchyProduct {
    
    private HierarchiesHierarchyProductCharacteristic[] characteristicField;
    
    private HierarchiesHierarchyProductAction actionField;
    
    private string parentField;
    
    private string toParentField;
    
    private string idField;
    
    private string newIDField;
    
    private string nameField;
    
    private string descriptionField;
    
    private HierarchiesHierarchyProductType typeField;
    
    private string sizeCodePrimaryField;
    
    private string sizeCodeSecondaryField;
    
    private string sizeCodeProductCategoryField;
    
    private string replaceWithField;
    
    private bool forceDeleteField;
    
    private string oTSForecastLevelHierarchyField;
    
    private HierarchiesHierarchyProductOTSForecastLevelSelect oTSForecastLevelSelectField;
    
    private bool oTSForecastLevelSelectFieldSpecified;
    
    private string oTSForecastLevelField;
    
    private HierarchiesHierarchyProductOTSForecastNodeSearch oTSForecastNodeSearchField;
    
    private bool oTSForecastNodeSearchFieldSpecified;
    
    private string oTSForecastStartsWithField;
    
    private string applyNodePropertiesField;
    
    public HierarchiesHierarchyProduct() {
        this.actionField = HierarchiesHierarchyProductAction.Update;
        this.typeField = HierarchiesHierarchyProductType.Undefined;
        this.forceDeleteField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Characteristic")]
    public HierarchiesHierarchyProductCharacteristic[] Characteristic {
        get {
            return this.characteristicField;
        }
        set {
            this.characteristicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(HierarchiesHierarchyProductAction.Update)]
    public HierarchiesHierarchyProductAction Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Parent {
        get {
            return this.parentField;
        }
        set {
            this.parentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ToParent {
        get {
            return this.toParentField;
        }
        set {
            this.toParentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NewID {
        get {
            return this.newIDField;
        }
        set {
            this.newIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(HierarchiesHierarchyProductType.Undefined)]
    public HierarchiesHierarchyProductType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodePrimary {
        get {
            return this.sizeCodePrimaryField;
        }
        set {
            this.sizeCodePrimaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeSecondary {
        get {
            return this.sizeCodeSecondaryField;
        }
        set {
            this.sizeCodeSecondaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeProductCategory {
        get {
            return this.sizeCodeProductCategoryField;
        }
        set {
            this.sizeCodeProductCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReplaceWith {
        get {
            return this.replaceWithField;
        }
        set {
            this.replaceWithField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ForceDelete {
        get {
            return this.forceDeleteField;
        }
        set {
            this.forceDeleteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OTSForecastLevelHierarchy {
        get {
            return this.oTSForecastLevelHierarchyField;
        }
        set {
            this.oTSForecastLevelHierarchyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public HierarchiesHierarchyProductOTSForecastLevelSelect OTSForecastLevelSelect {
        get {
            return this.oTSForecastLevelSelectField;
        }
        set {
            this.oTSForecastLevelSelectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OTSForecastLevelSelectSpecified {
        get {
            return this.oTSForecastLevelSelectFieldSpecified;
        }
        set {
            this.oTSForecastLevelSelectFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OTSForecastLevel {
        get {
            return this.oTSForecastLevelField;
        }
        set {
            this.oTSForecastLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public HierarchiesHierarchyProductOTSForecastNodeSearch OTSForecastNodeSearch {
        get {
            return this.oTSForecastNodeSearchField;
        }
        set {
            this.oTSForecastNodeSearchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OTSForecastNodeSearchSpecified {
        get {
            return this.oTSForecastNodeSearchFieldSpecified;
        }
        set {
            this.oTSForecastNodeSearchFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OTSForecastStartsWith {
        get {
            return this.oTSForecastStartsWithField;
        }
        set {
            this.oTSForecastStartsWithField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ApplyNodeProperties {
        get {
            return this.applyNodePropertiesField;
        }
        set {
            this.applyNodePropertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public partial class HierarchiesHierarchyProductCharacteristic {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public enum HierarchiesHierarchyProductAction {
    
    /// <remarks/>
    Update,
    
    /// <remarks/>
    Move,
    
    /// <remarks/>
    Delete,
    
    /// <remarks/>
    Rename,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public enum HierarchiesHierarchyProductType {
    
    /// <remarks/>
    Undefined,
    
    /// <remarks/>
    Hardlines,
    
    /// <remarks/>
    Softlines,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public enum HierarchiesHierarchyProductOTSForecastLevelSelect {
    
    /// <remarks/>
    Undefined,
    
    /// <remarks/>
    Level,
    
    /// <remarks/>
    Node,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public enum HierarchiesHierarchyProductOTSForecastNodeSearch {
    
    /// <remarks/>
    Undefined,
    
    /// <remarks/>
    ID,
    
    /// <remarks/>
    Name,
    
    /// <remarks/>
    Description,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HierarchyLoadSchema.xsd")]
public enum HierarchiesHierarchyType {
    
    /// <remarks/>
    Organizational,
    
    /// <remarks/>
    Open,
}
