//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd", IsNullable=false)]
public partial class ProductAmounts {
    
    private ProductAmountsOptions optionsField;
    
    private ProductAmountsProductAmount[] productAmountField;
    
    /// <remarks/>
    public ProductAmountsOptions Options {
        get {
            return this.optionsField;
        }
        set {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProductAmount")]
    public ProductAmountsProductAmount[] ProductAmount {
        get {
            return this.productAmountField;
        }
        set {
            this.productAmountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public partial class ProductAmountsOptions {
    
    private string salesEndingDateField;
    
    private bool rollStoreDailyToWeeklyField;
    
    private bool rollStoreDailyToWeeklyFieldSpecified;
    
    private bool rollStoreDailyUpHierarchyField;
    
    private bool rollStoreDailyUpHierarchyFieldSpecified;
    
    private bool rollStoreWeeklyUpHierarchyField;
    
    private bool rollStoreWeeklyUpHierarchyFieldSpecified;
    
    private bool rollStoreToChainField;
    
    private bool rollStoreToChainFieldSpecified;
    
    private bool rollChainUpHierarchyField;
    
    private bool rollChainUpHierarchyFieldSpecified;
    
    private bool rollIntransitField;
    
    private bool rollIntransitFieldSpecified;
    
    private bool rollStockForwardField;
    
    private bool rollStockForwardFieldSpecified;
    
    private string computationModelField;
    
    private ProductAmountsOptionsTransactionHint transactionHintField;
    
    public ProductAmountsOptions() {
        this.transactionHintField = ProductAmountsOptionsTransactionHint.NotSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SalesEndingDate {
        get {
            return this.salesEndingDateField;
        }
        set {
            this.salesEndingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RollStoreDailyToWeekly {
        get {
            return this.rollStoreDailyToWeeklyField;
        }
        set {
            this.rollStoreDailyToWeeklyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollStoreDailyToWeeklySpecified {
        get {
            return this.rollStoreDailyToWeeklyFieldSpecified;
        }
        set {
            this.rollStoreDailyToWeeklyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RollStoreDailyUpHierarchy {
        get {
            return this.rollStoreDailyUpHierarchyField;
        }
        set {
            this.rollStoreDailyUpHierarchyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollStoreDailyUpHierarchySpecified {
        get {
            return this.rollStoreDailyUpHierarchyFieldSpecified;
        }
        set {
            this.rollStoreDailyUpHierarchyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RollStoreWeeklyUpHierarchy {
        get {
            return this.rollStoreWeeklyUpHierarchyField;
        }
        set {
            this.rollStoreWeeklyUpHierarchyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollStoreWeeklyUpHierarchySpecified {
        get {
            return this.rollStoreWeeklyUpHierarchyFieldSpecified;
        }
        set {
            this.rollStoreWeeklyUpHierarchyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RollStoreToChain {
        get {
            return this.rollStoreToChainField;
        }
        set {
            this.rollStoreToChainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollStoreToChainSpecified {
        get {
            return this.rollStoreToChainFieldSpecified;
        }
        set {
            this.rollStoreToChainFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RollChainUpHierarchy {
        get {
            return this.rollChainUpHierarchyField;
        }
        set {
            this.rollChainUpHierarchyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollChainUpHierarchySpecified {
        get {
            return this.rollChainUpHierarchyFieldSpecified;
        }
        set {
            this.rollChainUpHierarchyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RollIntransit {
        get {
            return this.rollIntransitField;
        }
        set {
            this.rollIntransitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollIntransitSpecified {
        get {
            return this.rollIntransitFieldSpecified;
        }
        set {
            this.rollIntransitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RollStockForward {
        get {
            return this.rollStockForwardField;
        }
        set {
            this.rollStockForwardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RollStockForwardSpecified {
        get {
            return this.rollStockForwardFieldSpecified;
        }
        set {
            this.rollStockForwardFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ComputationModel {
        get {
            return this.computationModelField;
        }
        set {
            this.computationModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ProductAmountsOptionsTransactionHint.NotSpecified)]
    public ProductAmountsOptionsTransactionHint TransactionHint {
        get {
            return this.transactionHintField;
        }
        set {
            this.transactionHintField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public enum ProductAmountsOptionsTransactionHint {
    
    /// <remarks/>
    NotSpecified,
    
    /// <remarks/>
    All,
    
    /// <remarks/>
    StyleAndAbove,
    
    /// <remarks/>
    Color,
    
    /// <remarks/>
    Size,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public partial class ProductAmountsProductAmount {
    
    private ProductAmountsProductAmountVariableAmount[] variableAmountField;
    
    private ProductAmountsProductAmountPeriod periodField;
    
    private string versionField;
    
    private string productField;
    
    private string storeField;
    
    private ProductAmountsProductAmountDateType dateTypeField;
    
    private string dateField;
    
    private string parentField;
    
    private string sizeCodePrimaryField;
    
    private string sizeCodeSecondaryField;
    
    private string sizeCodeProductCategoryField;
    
    private string productDescriptionField;
    
    private string productNameField;
    
    public ProductAmountsProductAmount() {
        this.periodField = ProductAmountsProductAmountPeriod.Week;
        this.versionField = "Actual";
        this.storeField = "Chain";
        this.dateTypeField = ProductAmountsProductAmountDateType.Calendar;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VariableAmount")]
    public ProductAmountsProductAmountVariableAmount[] VariableAmount {
        get {
            return this.variableAmountField;
        }
        set {
            this.variableAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ProductAmountsProductAmountPeriod.Week)]
    public ProductAmountsProductAmountPeriod Period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Actual")]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Chain")]
    public string Store {
        get {
            return this.storeField;
        }
        set {
            this.storeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ProductAmountsProductAmountDateType.Calendar)]
    public ProductAmountsProductAmountDateType DateType {
        get {
            return this.dateTypeField;
        }
        set {
            this.dateTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Parent {
        get {
            return this.parentField;
        }
        set {
            this.parentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodePrimary {
        get {
            return this.sizeCodePrimaryField;
        }
        set {
            this.sizeCodePrimaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeSecondary {
        get {
            return this.sizeCodeSecondaryField;
        }
        set {
            this.sizeCodeSecondaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCodeProductCategory {
        get {
            return this.sizeCodeProductCategoryField;
        }
        set {
            this.sizeCodeProductCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductDescription {
        get {
            return this.productDescriptionField;
        }
        set {
            this.productDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductName {
        get {
            return this.productNameField;
        }
        set {
            this.productNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public partial class ProductAmountsProductAmountVariableAmount {
    
    private string variableField;
    
    private string amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Variable {
        get {
            return this.variableField;
        }
        set {
            this.variableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public enum ProductAmountsProductAmountPeriod {
    
    /// <remarks/>
    Week,
    
    /// <remarks/>
    Day,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public enum ProductAmountsProductAmountDateType {
    
    /// <remarks/>
    Calendar,
    
    /// <remarks/>
    Fiscal,
}
