//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RelieveIntransitSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/RelieveIntransitSchema.xsd", IsNullable=false)]
public class RelieveIntransits {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelieveIntransit")]
    public RelieveIntransitsRelieveIntransit[] RelieveIntransit;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RelieveIntransitSchema.xsd")]
public class RelieveIntransitsRelieveIntransit {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RelieveStore")]
    public RelieveIntransitsRelieveIntransitRelieveStore[] RelieveStore;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string HeaderID;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductID;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RelieveIntransitSchema.xsd")]
public class RelieveIntransitsRelieveIntransitRelieveStore {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreID;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Double Units;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RelieveAllStores;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RelieveAllStoresSpecified;
}
