//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RollupSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/RollupSchema.xsd", IsNullable=false)]
public class Requests {
    
    /// <remarks/>
    public RequestsOptions Options;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Variables")]
    public RequestsVariables[] Variables;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Request")]
    public RequestsRequest[] Request;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RollupSchema.xsd")]
public class RequestsOptions {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(RequestsOptionsRollupDays.All)]
    public RequestsOptionsRollupDays RollupDays = RequestsOptionsRollupDays.All;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool HonorLocks = false;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RollupSchema.xsd")]
public enum RequestsOptionsRollupDays {
    
    /// <remarks/>
    Current,
    
    /// <remarks/>
    All,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RollupSchema.xsd")]
public class RequestsRequest {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(RequestsRequestType.Level)]
    public RequestsRequestType Type = RequestsRequestType.Level;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Product;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Actual")]
    public string Version = "Actual";
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(RequestsRequestData.All)]
    public RequestsRequestData Data = RequestsRequestData.All;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(RequestsRequestPeriod.Week)]
    public RequestsRequestPeriod Period = RequestsRequestPeriod.Week;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(RequestsRequestDateType.Calendar)]
    public RequestsRequestDateType DateType = RequestsRequestDateType.Calendar;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FromDate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ToDate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ToLevel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FromLevel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool OverrideVariableLevels = false;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RollupSchema.xsd")]
public enum RequestsRequestType {
    
    /// <remarks/>
    Level,
    
    /// <remarks/>
    StoreToChain,
    
    /// <remarks/>
    Posting,
    
    /// <remarks/>
    Reclass,
    
    /// <remarks/>
    Intransit,
    
    /// <remarks/>
    DayToWeek,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RollupSchema.xsd")]
public enum RequestsRequestData {
    
    /// <remarks/>
    All,
    
    /// <remarks/>
    Store,
    
    /// <remarks/>
    Chain,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RollupSchema.xsd")]
public enum RequestsRequestPeriod {
    
    /// <remarks/>
    Week,
    
    /// <remarks/>
    Day,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RollupSchema.xsd")]
public enum RequestsRequestDateType {
    
    /// <remarks/>
    Calendar,
    
    /// <remarks/>
    Fiscal,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/RollupSchema.xsd")]
public class RequestsVariables {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ChainHistoryLevel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ChainForecastLevel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreDailyHistoryLevel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreWeeklyHistoryLevel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreForecastLevel;
}
