//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveLoadStatusSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SizeCurveLoadStatusSchema.xsd", IsNullable=false)]
public class SizeCurveLoadStatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SizeCurveStatus")]
    public SizeCurveLoadStatusSizeCurveStatus[] SizeCurveStatus;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveLoadStatusSchema.xsd")]
public class SizeCurveLoadStatusSizeCurveStatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCurveGroupName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool LoadStatus;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LoadStatusSpecified;
}
