//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveLoadSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SizeCurveLoadSchema.xsd", IsNullable=false)]
public class SizeCurves {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SizeCurve")]
    public SizeCurvesSizeCurve[] SizeCurve;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveLoadSchema.xsd")]
public class SizeCurvesSizeCurve {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("StoreSizeCurve")]
    public SizeCurvesSizeCurveStoreSizeCurve[] StoreSizeCurve;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCurveGroupName;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveLoadSchema.xsd")]
public class SizeCurvesSizeCurveStoreSizeCurve {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StoreID;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCurveName;
}
