//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeConstraintsLoadSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SizeConstraintsLoadSchema.xsd", IsNullable=false)]
public class SizeConstraintsModels {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SizeConstraintsModel")]
    public SizeConstraintsModelsSizeConstraintsModel[] SizeConstraintsModel;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeConstraintsLoadSchema.xsd")]
public class SizeConstraintsModelsSizeConstraintsModel {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Set")]
    public SizeConstraintsModelsSizeConstraintsModelSet[] Set;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SizeConstraintsModelsSizeConstraintsModelAction Action;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ModelName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCurve;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeGroup;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Attribute;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeConstraintsLoadSchema.xsd")]
public class SizeConstraintsModelsSizeConstraintsModelSet {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SetName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ColorCode;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizePrimary;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeSecondary;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCode;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string SizeMin;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string SizeMax;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string SizeMult;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeConstraintsLoadSchema.xsd")]
public enum SizeConstraintsModelsSizeConstraintsModelAction {
    
    /// <remarks/>
    Create,
    
    /// <remarks/>
    Modify,
    
    /// <remarks/>
    Remove,
}
