//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2032.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveGroupLoadSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SizeCurveGroupLoadSchema.xsd", IsNullable=false)]
public class SizeCurveGroups {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SizeCurveGroup")]
    public SizeCurveGroupsSizeCurveGroup[] SizeCurveGroup;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveGroupLoadSchema.xsd")]
public class SizeCurveGroupsSizeCurveGroup {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SizeCurve")]
    public SizeCurveGroupsSizeCurveGroupSizeCurve[] SizeCurve;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCurveGroupName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SizeCurveGroupsSizeCurveGroupSizeCurveGroupAction SizeCurveGroupAction;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeCurveGroupActionSpecified;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveGroupLoadSchema.xsd")]
public class SizeCurveGroupsSizeCurveGroupSizeCurve {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Size")]
    public SizeCurveGroupsSizeCurveGroupSizeCurveSize[] Size;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SizeCurveName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductCategory;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SizeCurveGroupsSizeCurveGroupSizeCurveSizeCurveAction SizeCurveAction;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeCurveActionSpecified;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveGroupLoadSchema.xsd")]
public class SizeCurveGroupsSizeCurveGroupSizeCurveSize {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CodeID;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Primary;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Secondary;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Double Value;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValueSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SizeCurveGroupsSizeCurveGroupSizeCurveSizeSizeAction SizeAction;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeActionSpecified;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveGroupLoadSchema.xsd")]
public enum SizeCurveGroupsSizeCurveGroupSizeCurveSizeSizeAction {
    
    /// <remarks/>
    Create,
    
    /// <remarks/>
    Modify,
    
    /// <remarks/>
    Remove,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveGroupLoadSchema.xsd")]
public enum SizeCurveGroupsSizeCurveGroupSizeCurveSizeCurveAction {
    
    /// <remarks/>
    Create,
    
    /// <remarks/>
    Modify,
    
    /// <remarks/>
    Remove,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SizeCurveGroupLoadSchema.xsd")]
public enum SizeCurveGroupsSizeCurveGroupSizeCurveGroupAction {
    
    /// <remarks/>
    Create,
    
    /// <remarks/>
    Modify,
    
    /// <remarks/>
    Remove,
}
