//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/StoreLoadSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/StoreLoadSchema.xsd", IsNullable=false)]
public partial class Stores {
    
    private StoresOptions optionsField;
    
    private StoresStore[] storeField;
    
    /// <remarks/>
    public StoresOptions Options {
        get {
            return this.optionsField;
        }
        set {
            this.optionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Store")]
    public StoresStore[] Store {
        get {
            return this.storeField;
        }
        set {
            this.storeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/StoreLoadSchema.xsd")]
public partial class StoresOptions {
    
    private bool autoAddCharacteristicsField;
    
    private bool autoAddCharacteristicsFieldSpecified;
    
    private string characteristicDelimiterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool AutoAddCharacteristics {
        get {
            return this.autoAddCharacteristicsField;
        }
        set {
            this.autoAddCharacteristicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AutoAddCharacteristicsSpecified {
        get {
            return this.autoAddCharacteristicsFieldSpecified;
        }
        set {
            this.autoAddCharacteristicsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CharacteristicDelimiter {
        get {
            return this.characteristicDelimiterField;
        }
        set {
            this.characteristicDelimiterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/StoreLoadSchema.xsd")]
public partial class StoresStore {
    
    private StoresStoreCharacteristic[] characteristicField;
    
    private string idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private string cityField;
    
    private string stateField;
    
    private int sellingSquareFeetField;
    
    private bool sellingSquareFeetFieldSpecified;
    
    private System.DateTime sellingOpenDateField;
    
    private bool sellingOpenDateFieldSpecified;
    
    private System.DateTime sellingCloseDateField;
    
    private bool sellingCloseDateFieldSpecified;
    
    private System.DateTime stockOpenDateField;
    
    private bool stockOpenDateFieldSpecified;
    
    private System.DateTime stockCloseDateField;
    
    private bool stockCloseDateFieldSpecified;
    
    private bool activeIndicatorField;
    
    private bool activeIndicatorFieldSpecified;
    
    private int leadTimeField;
    
    private bool leadTimeFieldSpecified;
    
    private string shipDateField;
    
    private string vSWIDField;
    
    private StoresStoreAction actionField;
    
    public StoresStore() {
        this.actionField = StoresStoreAction.Update;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Characteristic")]
    public StoresStoreCharacteristic[] Characteristic {
        get {
            return this.characteristicField;
        }
        set {
            this.characteristicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SellingSquareFeet {
        get {
            return this.sellingSquareFeetField;
        }
        set {
            this.sellingSquareFeetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SellingSquareFeetSpecified {
        get {
            return this.sellingSquareFeetFieldSpecified;
        }
        set {
            this.sellingSquareFeetFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime SellingOpenDate {
        get {
            return this.sellingOpenDateField;
        }
        set {
            this.sellingOpenDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SellingOpenDateSpecified {
        get {
            return this.sellingOpenDateFieldSpecified;
        }
        set {
            this.sellingOpenDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime SellingCloseDate {
        get {
            return this.sellingCloseDateField;
        }
        set {
            this.sellingCloseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SellingCloseDateSpecified {
        get {
            return this.sellingCloseDateFieldSpecified;
        }
        set {
            this.sellingCloseDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime StockOpenDate {
        get {
            return this.stockOpenDateField;
        }
        set {
            this.stockOpenDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StockOpenDateSpecified {
        get {
            return this.stockOpenDateFieldSpecified;
        }
        set {
            this.stockOpenDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime StockCloseDate {
        get {
            return this.stockCloseDateField;
        }
        set {
            this.stockCloseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StockCloseDateSpecified {
        get {
            return this.stockCloseDateFieldSpecified;
        }
        set {
            this.stockCloseDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ActiveIndicator {
        get {
            return this.activeIndicatorField;
        }
        set {
            this.activeIndicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ActiveIndicatorSpecified {
        get {
            return this.activeIndicatorFieldSpecified;
        }
        set {
            this.activeIndicatorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int LeadTime {
        get {
            return this.leadTimeField;
        }
        set {
            this.leadTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LeadTimeSpecified {
        get {
            return this.leadTimeFieldSpecified;
        }
        set {
            this.leadTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ShipDate {
        get {
            return this.shipDateField;
        }
        set {
            this.shipDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VSWID {
        get {
            return this.vSWIDField;
        }
        set {
            this.vSWIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(StoresStoreAction.Update)]
    public StoresStoreAction Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/StoreLoadSchema.xsd")]
public partial class StoresStoreCharacteristic {
    
    private string nameField;
    
    private string valueField;
    
    private StoresStoreCharacteristicCharType charTypeField;
    
    public StoresStoreCharacteristic() {
        this.charTypeField = StoresStoreCharacteristicCharType.Text;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(StoresStoreCharacteristicCharType.Text)]
    public StoresStoreCharacteristicCharType CharType {
        get {
            return this.charTypeField;
        }
        set {
            this.charTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/StoreLoadSchema.xsd")]
public enum StoresStoreCharacteristicCharType {
    
    /// <remarks/>
    Text,
    
    /// <remarks/>
    Date,
    
    /// <remarks/>
    Number,
    
    /// <remarks/>
    Dollar,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/StoreLoadSchema.xsd")]
public enum StoresStoreAction {
    
    /// <remarks/>
    Update,
    
    /// <remarks/>
    Delete,
    
    /// <remarks/>
    Recover,
}
