//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/VSWLoadSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/VSWLoadSchema.xsd", IsNullable=false)]
public partial class VSW {
    
    private VSWMerchandise[] merchandiseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Merchandise")]
    public VSWMerchandise[] Merchandise {
        get {
            return this.merchandiseField;
        }
        set {
            this.merchandiseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/VSWLoadSchema.xsd")]
public partial class VSWMerchandise {
    
    private VSWMerchandiseStore[] storeField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Store")]
    public VSWMerchandiseStore[] Store {
        get {
            return this.storeField;
        }
        set {
            this.storeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/VSWLoadSchema.xsd")]
public partial class VSWMerchandiseStore {
    
    private string idField;
    
    private string minShipQtyField;
    
    private string pctThresholdField;
    
    private string itemMaxField;
    
    private string fWOSMaxValueField;
    
    private string fWOSMaxModelField;
    
    private string pushToBkStkField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MinShipQty {
        get {
            return this.minShipQtyField;
        }
        set {
            this.minShipQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PctThreshold {
        get {
            return this.pctThresholdField;
        }
        set {
            this.pctThresholdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ItemMax {
        get {
            return this.itemMaxField;
        }
        set {
            this.itemMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FWOSMaxValue {
        get {
            return this.fWOSMaxValueField;
        }
        set {
            this.fWOSMaxValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FWOSMaxModel {
        get {
            return this.fWOSMaxModelField;
        }
        set {
            this.fWOSMaxModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PushToBkStk {
        get {
            return this.pushToBkStkField;
        }
        set {
            this.pushToBkStkField = value;
        }
    }
}
