//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd", IsNullable=false)]
public class ProductAmounts {
    
    /// <remarks/>
    public ProductAmountsOptions Options;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProductAmount")]
    public ProductAmountsProductAmount[] ProductAmount;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public class ProductAmountsOptions {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SalesEndingDate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool UseBulkInsert = false;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool RollupValues = false;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool SumDaysToWeeks = false;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public class ProductAmountsProductAmountVariableAmount {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Variable;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Amount;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public class ProductAmountsProductAmount {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VariableAmount")]
    public ProductAmountsProductAmountVariableAmount[] VariableAmount;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ProductAmountsProductAmountPeriod.Week)]
    public ProductAmountsProductAmountPeriod Period = ProductAmountsProductAmountPeriod.Week;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Product;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Actual")]
    public string Version = "Actual";
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ProductAmountsProductAmountDateType.Calendar)]
    public ProductAmountsProductAmountDateType DateType = ProductAmountsProductAmountDateType.Calendar;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Date;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Chain")]
    public string Store = "Chain";
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Parent;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public enum ProductAmountsProductAmountPeriod {
    
    /// <remarks/>
    Week,
    
    /// <remarks/>
    Day,
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/HistoryPlanLoadSchema.xsd")]
public enum ProductAmountsProductAmountDateType {
    
    /// <remarks/>
    Calendar,
    
    /// <remarks/>
    Fiscal,
}
